import test from 'node:test';import assert from 'node:assert/strict';
import {createPokerMedia} from '../src/garage3d/poker/callMedia.ts';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function stream(){const track={stopped:false,stop(){this.stopped=true;}};return {track,getTracks:()=>[track]};}
function fixture(overrides={}){const published=[],unpublished=[];let captures=0;const media=createPokerMedia({acquire:async()=>{captures++;return stream();},mask:async()=>stream(),publish:async t=>{published.push(t);},unpublish:async t=>{unpublished.push(t);},changed:()=>{},...overrides});return {media,published,unpublished,get captures(){return captures;}};}
test('joining creates no captures; mask is composed before publish and raw is never published',async()=>{const raw=stream(),masked=stream(),f=fixture({acquire:async()=>raw,mask:async input=>{assert.equal(input,raw);return masked;}});assert.equal(f.captures,0);await f.media.on('video',true);assert.deepEqual(f.published,[masked.track]);await f.media.stop();assert.equal(masked.track.stopped,true);});
test('mask failure closes raw and publishes nothing',async()=>{const raw=stream(),f=fixture({acquire:async()=>raw,mask:async()=>{throw Error('tracker failed');}});await assert.rejects(f.media.on('video',true));assert.equal(raw.track.stopped,true);assert.equal(f.published.length,0);});
test('leaving while permission prompt is pending closes the late capture',async()=>{const capture=deferred(),raw=stream(),f=fixture({acquire:()=>capture.promise});const on=f.media.on('video',false);await new Promise(r=>setImmediate(r));await f.media.stop();capture.resolve(raw);await on;assert.equal(raw.track.stopped,true);assert.equal(f.published.length,0);});
test('leaving during mask initialization stops both streams without publishing',async()=>{const mask=deferred(),raw=stream(),masked=stream(),f=fixture({acquire:async()=>raw,mask:()=>mask.promise});const on=f.media.on('video',true);await new Promise(r=>setImmediate(r));await f.media.stop();assert.equal(raw.track.stopped,true);mask.resolve(masked);await on;assert.equal(masked.track.stopped,true);assert.equal(f.published.length,0);});
test('late publication is revoked and mic stays independent from video',async()=>{const publication=deferred(),raw=stream(),f=fixture({acquire:async()=>raw,publish:()=>publication.promise});const on=f.media.on('video',false);await new Promise(r=>setImmediate(r));await f.media.stop();publication.resolve();await on;assert.equal(raw.track.stopped,true);assert.deepEqual(f.unpublished,[raw.track]);const g=fixture();await g.media.on('audio',false);await g.media.on('video',false);await g.media.off('video');assert.ok(g.media.get('audio'));await g.media.stop();assert.equal(g.media.get('audio'),undefined);});
